[package]
name = "rust-lox"
version = "0.1.0"
authors = ["laegel"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "loxlib"
path = "src/lib.rs"

[[bin]]
name = "loxbin"
path = "src/bin/repl.rs"

[dependencies]
